const curiosities = [
    "Un solo rayo contiene suficiente energía para tostar 100,000 rebanadas de pan.",
    "En Japón, existe una isla llamada Okunoshima que está completamente llena de conejos amigables.",
    "Las medusas Turritopsis dohrnii son biológicamente inmortales; pueden revertir su ciclo de vida indefinidamente.",
    "El corazón de un camarón está en su cabeza.",
    "En la antigua Roma, la orina se utilizaba para blanquear ropa y lavar dientes debido al amoníaco que contiene.",
    "Los astronautas en el espacio pueden crecer hasta 5 centímetros debido a la falta de gravedad.",
    "Un grupo de cuervos se llama 'un asesinato'.",
    "La Universidad de Oxford es más antigua que el Imperio Azteca.",
    "El polvo espacial que cae sobre la Tierra cada año pesa alrededor de 40,000 toneladas.",
    "Las hormigas nunca duermen; solo toman pequeños periodos de descanso.",
    "Los cerdos no pueden mirar hacia el cielo debido a la forma de su cuello.",
    "Las mariposas monarca pueden volar hasta 4,000 kilómetros durante su migración anual.",
    "El cerebro humano tiene el mismo nivel de electricidad que una bombilla de 10 vatios.",
    "Un solo árbol puede liberar suficiente oxígeno para que vivan dos personas durante un año.",
    "Las jirafas tienen la misma cantidad de vértebras en el cuello que los humanos (siete).",
    "La mayoría del oro en la Tierra provino de meteoritos que cayeron hace más de 4,000 millones de años.",
    "Los tiburones pueden detectar una gota de sangre en una piscina olímpica.",
    "La mayoría de los fuegos artificiales que ves contienen metales que les dan sus colores brillantes.",
    "Los gatos tienen 32 músculos en cada oreja.",
    "El Monte Everest crece aproximadamente 4 milímetros cada año debido a la actividad tectónica.",
    "Los pulpos tienen tres corazones y su sangre es azul debido al cobre en su hemocianina.",
    "El ADN humano es 60% similar al de un plátano.",
    "Un solo copo de nieve puede tener hasta 180 millones de moléculas de agua.",
    "Los delfines tienen nombres únicos para llamarse entre sí.",
    "La miel nunca se echa a perder; se han encontrado tarros de miel en tumbas egipcias de más de 3,000 años que siguen siendo comestibles.",
    "Los tiburones han existido en la Tierra por más de 400 millones de años, mucho antes que los dinosaurios.",
    "Las cebras no tienen rayas negras y blancas; en realidad, su piel es negra con rayas blancas.",
    "Los koalas duermen alrededor de 20 horas al día.",
    "Los mosquitos son responsables de más muertes humanas que cualquier otro animal en el mundo.",
    "Los elefantes son uno de los pocos animales que pueden reconocerse en un espejo.",
    "Las estrellas de mar no tienen cerebro.",
    "Las abejas pueden reconocer rostros humanos.",
    "La Gran Muralla China no es visible desde el espacio sin ayuda.",
    "El chocolate era utilizado como moneda en la antigua civilización maya.",
    "El agua constituye aproximadamente el 71% de la superficie de la Tierra.",
    "Las mariposas solo pueden ver el color rojo, verde y amarillo.",
    "Las cebras no pueden dormir solas; siempre necesitan estar en grupo para sentirse seguras.",
    "Los pingüinos emperador pueden sumergirse a más de 500 metros de profundidad y aguantar la respiración por más de 20 minutos.",
    "Las ranas pueden congelarse completamente en invierno y volver a la vida en primavera.",
    "El sonido viaja cuatro veces más rápido en el agua que en el aire.",
    "La piel de un tigre es rayada, al igual que su pelaje.",
    "Las arañas no pueden volar, pero algunas pueden 'volar' usando hilos de seda para moverse con el viento.",
    "Los caracoles pueden dormir hasta tres años seguidos.",
    "Los ojos de los camaleones pueden moverse en dos direcciones diferentes al mismo tiempo.",
    "El bambú puede crecer hasta 91 centímetros en un solo día.",
    "El cerebro humano genera suficiente electricidad como para encender una bombilla pequeña.",
    "Los plátanos son ligeramente radiactivos debido al potasio que contienen.",
    "El koala tiene huellas dactilares casi idénticas a las de los humanos.",
    "La palabra más larga en inglés tiene 189,819 letras y se tarda más de 3 horas en pronunciarla.",
    "La temperatura más baja registrada en la Tierra fue de -128.6°F (-89.2°C) en la Antártida en 1983.",
    "Los osos polares son en realidad de piel negra bajo su pelaje blanco.",
    "El sonido del crujido al caminar sobre nieve se debe a la compresión de los cristales de hielo.",
    "Las cebras son blancas con rayas negras, no negras con rayas blancas.",
    "El primer animal clonado fue una rana en 1952.",
    "Los ratones pueden reproducirse tan rápido que en un año una pareja puede tener más de 5,000 descendientes.",
    "Las cebras son más rápidas que los caballos en distancias cortas."
];

// Función para mostrar una curiosidad aleatoria
function displayRandomCuriosity() {
    const randomIndex = Math.floor(Math.random() * curiosities.length);
    document.getElementById('curiosity').innerText = curiosities[randomIndex];
}

document.addEventListener('DOMContentLoaded', displayRandomCuriosity);
